# Generated by Django 4.1.6 on 2023-02-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='description',
            field=models.CharField(default='Sem descrição', max_length=1000),
        ),
        migrations.AddField(
            model_name='courses',
            name='title',
            field=models.CharField(default='Sem título', max_length=255),
        ),
        migrations.AlterField(
            model_name='courses',
            name='duration',
            field=models.IntegerField(default=1),
        ),
    ]
