# Generated by Django 4.1.6 on 2023-02-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('father', models.CharField(max_length=255)),
                ('mother', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=11)),
                ('serie_year', models.CharField(choices=[(1, 'Sexto Ano'), (2, 'Sétimo Ano'), (3, 'Oitavo Ano'), (4, 'Nono Ano'), (5, 'Primeiro Ano'), (6, 'Segundo Ano'), (7, 'Terceiro Ano')], default=1, max_length=1)),
            ],
        ),
    ]
