# Generated by Django 4.1.6 on 2023-02-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='serie_year',
            field=models.CharField(choices=[('1', 'Sexto Ano'), ('2', 'Sétimo Ano'), ('3', 'Oitavo Ano'), ('4', 'Nono Ano'), ('5', 'Primeiro Ano'), ('6', 'Segundo Ano'), ('7', 'Terceiro Ano')], default=1, max_length=1),
        ),
    ]
