# Generated by Django 4.1.6 on 2023-02-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_courses_description_courses_title_and_more'),
        ('students', '0003_students_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='students',
        ),
        migrations.AddField(
            model_name='students',
            name='courses',
            field=models.ManyToManyField(related_name='students', to='courses.courses'),
        ),
    ]
